travis:
  secure:
    BINSTAR_TOKEN: TZ3y562jf4oa5TsMa8KDzW8s4/TXFhOft6uTtx4ctS5e+XrvaX/gESSZZeqWOT2UUsw3RLdkGSqmXRctXk3ADmbWC2sMjYbtuZaIPwHXFeYUJov1th1cydnKFL3zF8p1ifu805knegQbsTTvbbSdNs7y1srkLXp6Ba9AQxX16TThAw046tJEv8pOAkJgvNgZTy4S/0GY3MUeYuTUzhuqDZI+EH3J6P7d9c+omt/RISSt9OPtRx8b7vZGxOu58btUXkmCtC2phXg9cCWahfiHL7F8CdJ9yrcy/HdmfbS20IRXZx4UnOTIQb+hPXbHN7CED23jEpDiOl1fKGY4vEQzwvLjHAMhdfA4Mi62ISCMryBKGFfAIcNbtb1gNmipm2QJkEsBPSnSUT8Ea/eyH/yvKGHjXBN6TRlerfxxzgpKvrSsIjPC+3rkA/E/ajpBXbFB5o0XTNz+buqa1sKizuzFYqoI7sKqcsIpZHjlt4P5KXjAbz+lz2Zf6Ucd/Uy2XTf00aJ2bNLo+SVZjovrh87hylWJYrRQSR+6/cM1A8ybKLgelmLsiOWFY0HtdDb5UUfeEfz5Cz62IqtSz0t3JulHdR802mkToHgdR/miCNjseaaIzexqq1j0YMSmGvxX69vXXXkNTXkU10u/+uIH1VTUVEXanN6T8jTiWB0Xa/kFQa8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
