travis:
  secure:
    BINSTAR_TOKEN: k9/i9K7y/eaowG1BMjlE13SyXGCcrTrO889qk4LRIbCurKXliDuXwvHI/Srq7neZrIYzbzFRMXHLl3x2WzNU+291iyelee5IrE6Q48ZFwLr1kXS3nRbeMb2QDvUe5Kr0tRpvvQnAIXxA26OOjSCrp88ak+d2VAOTDatnc2Kdvygldfw3PySA6pibQ/Xbv0zkUzjj1J4lDeNJqNCUfxCblfd3bBs9iDL1JDki0PRCjmAgScJ09r4NdKzyw+7WooZFvKqhRS/2g7CVEk2lWaE78bOGJTH65xpD3LRy4UddV09QpP+IH8o662HoYA9JJck6d+o1FJBsdl/pscQKwiyRMwywLnMNXvTalNV0H4skGZw8a7yoKcTZ+2kUlPSwfwQ3PLHHNlFamOa5zSfNmdHjivLIMOrGCnv74/oN3+Slrz1OE1cCPmCokb1U9Cf9OGQDW2UWAliW+U1ERssRlEAPcul4G7mDUn7fATVTUdBXE4PCB3FEUiilcWUKafBIOjNaZFxuIvpsyXkalsx5zBp2Sg2K7bT/h8t9p9EfZyPJzokNE84ozhVdoCsXndzBxiND03y5e4GFxpK7Ny5TcZg7da6Hhb/pWSJLYR6n/TX9CKd+i0gY924tNcHyf2W9kcmGWZ0NmQIYUalfJ4ZVOAuKISITWH4FocVk7Z7QNaVu+Vc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
